# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typecho_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time']},
        ),
    ]
