# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171121_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecho_post',
            name='created_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='typecho_post',
            name='modified_time',
            field=models.IntegerField(),
        ),
    ]
