# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171121_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecho_post',
            name='modified_time',
        ),
    ]
