# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_typecho_post_modified_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Typecho_Post',
        ),
    ]
