# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_typecho_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typecho_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('created_time', models.IntegerField()),
                ('modified_time', models.IntegerField()),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('authorId', models.IntegerField()),
                ('template', models.IntegerField(blank=True)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('commentsNum', models.IntegerField(blank=True)),
                ('allowPing', models.IntegerField(blank=True)),
                ('allowFeed', models.IntegerField(blank=True)),
                ('parent', models.IntegerField()),
                ('views', models.IntegerField()),
                ('orrinid', models.IntegerField()),
                ('allowComments', models.IntegerField(blank=True, default=b'1')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
