# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_typecho_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecho_post',
            name='allowComments',
        ),
        migrations.AddField(
            model_name='typecho_post',
            name='allowComment',
            field=models.CharField(blank=True, default=b'0', max_length=255),
        ),
        migrations.AlterField(
            model_name='typecho_post',
            name='allowFeed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='typecho_post',
            name='allowPing',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
