# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171122_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecho_post',
            old_name='order',
            new_name='order_num',
        ),
    ]
