# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171122_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecho_post',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='typecho_post',
            name='template',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
