# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171122_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecho_post',
            name='orrinid',
            field=models.IntegerField(null=True),
        ),
    ]
