# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171122_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typecho_Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('created_time', models.IntegerField()),
                ('modified_time', models.IntegerField()),
                ('text', models.TextField()),
                ('commentsNum', models.IntegerField(blank=True)),
                ('allowComment', models.CharField(blank=True, default=b'0', max_length=255)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
