# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_typecho_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecho_posts',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
