# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_typecho_posts_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Typecho_Post',
        ),
    ]
